services:
  postgres:
    image: postgres:16
    container_name: postgres-devspace
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devspace
    ports:
      - "5432:5432"
    volumes:
      - pg_data_devspace:/var/lib/postgresql/data

volumes:
  pg_data_devspace:
